class DouyinAweme(Base):
    __tablename__ = 'douyin_aweme'
    id = Column(Integer, primary_key=True, autoincrement=True, comment='自增ID')
    user_id = Column(String(64), nullable=True, comment='用户ID')
    sec_uid = Column(String(128), nullable=True, comment='用户sec_uid')
    short_user_id = Column(String(64), nullable=True, comment='用户短ID')
    user_unique_id = Column(String(64), nullable=True, comment='用户唯一ID')
    nickname = Column(String(64), nullable=True, comment='用户昵称')
    avatar = Column(String(255), nullable=True, comment='用户头像地址')
    user_signature = Column(String(500), nullable=True, comment='用户签名')
    ip_location = Column(String(255), nullable=True, comment='评论时的IP地址')
    add_ts = Column(BigInteger, nullable=False, comment='记录添加时间戳')
    last_modify_ts = Column(BigInteger, nullable=False, comment='记录最后修改时间戳')
    aweme_id = Column(String(64), nullable=False, comment='视频ID')
    aweme_type = Column(String(16), nullable=False, comment='视频类型')
    title = Column(Text, nullable=True, comment='视频标题')
    desc = Column(Text, nullable=True, comment='视频描述')
    create_time = Column(BigInteger, nullable=False, comment='视频发布时间戳')
    liked_count = Column(String(16), nullable=True, comment='视频点赞数')
    comment_count = Column(String(16), nullable=True, comment='视频评论数')
    share_count = Column(String(16), nullable=True, comment='视频分享数')
    collected_count = Column(String(16), nullable=True, comment='视频收藏数')
    aweme_url = Column(String(255), nullable=True, comment='视频详情页URL')
    source_keyword = Column(String(255), nullable=False, default='', comment='搜索来源关键字')
    add_time = Column(String(32), nullable=True, comment='记录添加时间')
    last_modify_time = Column(String(32), nullable=True, comment='记录最后修改时间')
    create_date_time = Column(String(32), nullable=True, comment='视频发布时间') 